### ISSUE TITLE
[Bug]: No works. Here is error

### ISSUE THREAD

**Issue by axemaster** [sdwebui-w-horde/sd-webui-stable-horde-worker#100]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

Imagine my sad face when I see this stack filling my console again and again until Python crashes.

```
Traceback (most recent call last):
  File "/Users/userguy/work/somefolder/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/horde.py", line 194, in run
    req = await HordeJob.get(
  File "/Users/userguy/work/somefolder/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/job.py", line 221, in get
    req = await r.json()
  File "/Users/userguy/work/somefolder/stable-diffusion-webui/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://stablehorde.net/api/v2/generate/pop')
```

### Steps to reproduce

install latest version of ext (i.e. this). Enable the worker ext. Exit and re-run A1111.

Can't tell if problem is with the ext, A1111, or the horde API itself. I use a script to launch A1111 than enables the worker in the ext config.json and then pulls the latest from the A1111 and all extension repos, then launches A1111 itself.

```
Traceback (most recent call last):
  File "/Users/userguy/work/somefolder/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/horde.py", line 194, in run
    req = await HordeJob.get(
  File "/Users/userguy/work/somefolder/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/job.py", line 221, in get
    req = await r.json()
  File "/Users/userguy/work/somefolder/stable-diffusion-webui/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://stablehorde.net/api/v2/generate/pop')

```

### What did you expect to happen?

It works as usual. Lots of joy. Now, no joy.

### Stable Diffusion WebUI Commit SHA

latest as of the date-time of this issue.

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Additional information

Not a browser issue. Launching from shell. Don't even open the browser.
I have over 1/2 million kudos thanks to this ext so It definitely has worked great most of the time!

**Comment by axemaster** [comment]
Update: now it's accepted 8 of the last 100 or so requests. I scripted A1111 to restart after crashing.

**Comment by db0** [comment]
FYI: We had a horde downtime

**Comment by MaikoTan** [comment]
Hmmmm....It is worth to handle the error though.
