### ISSUE TITLE
[Bug]: module 'modules.txt2img' has no attribute 'StableDiffusionProcessingTxt2Img'

### ISSUE THREAD

**Issue by axemaster** [sdwebui-w-horde/sd-webui-stable-horde-worker#103]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

It worked a day or two ago. I updated as usual and ran it tonight, I get this, it just repeats indefinitely.

Traceback (most recent call last):
  File "/Users/timshea/work/A1111-horde/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/horde.py", line 202, in run
    await self.handle_request(req)
  File "/Users/timshea/work/A1111-horde/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/horde.py", line 353, in handle_request
    p = txt2img.StableDiffusionProcessingTxt2Img(**params)
AttributeError: module 'modules.txt2img' has no attribute 'StableDiffusionProcessingTxt2Img'

### Steps to reproduce

pull the latest A1111 and extension. Run it. Enable the horde worker.

### What did you expect to happen?

worker ext to accept and process stable horde jobs

### Stable Diffusion WebUI Commit SHA

latest as of the date of this issue creation

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Other

### Additional information

Not a browser issue. Running from shell (zsh).

**Comment by axemaster** [comment]
testing

**Comment by axemaster** [comment]
Fixed! TY
